name: Build & Push Docker image

on:
  workflow_run:
    workflows: ["test"]
    types: [completed]    # testワークフローが完了したら起動
  workflow_dispatch:      # 手動実行

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: 0nulu/titanic-ml-pipeline:latest