name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Python 3.10 で統一（3.8+ バッジはそのまま OK）
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 依存インストール + Ruff
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # コードスタイルチェック (Ruff)
    - name: Lint with ruff
      run: |
        ruff .

    # パイプライン実行（Makefile）
    - name: Run Titanic ML pipeline
      run: |
        make all

    # submission.csv をアーティファクトとして保存
    - name: Upload submission artifact
      uses: actions/upload-artifact@v3
      with:
        name: submission
        path: submission.csv
