name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # 2. Python のセットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      # 3. 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 前処理を実行
      - name: Run preprocessing
        run: python src/preprocess.py

      # 5. 推論＆提出ファイルの生成
      - name: Run evaluation
        run: python src/evaluate.py
