jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to staging
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull 0nulu/titanic-ml-pipeline:latest
            docker run --rm -v /home/ec2-user/data:/app/data 0nulu/titanic-ml-pipeline:latest