# .github/workflows/deploy-staging.yml
name: Deploy to Staging

on:
  workflow_run:
    workflows: ["Build & Push Docker image"]  # CI ワークフロー名を指定
    types:
      - completed
  workflow_dispatch:    # 手動トリガー用（必要なら）

jobs:
  deploy-staging:
    # Build（docker.yml）の成功時だけ実行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }} 

      - name: SSH to staging
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1) S3 から最新データを取得
            aws s3 cp s3://my-titanic-data-bucket-2025/titanic/train.csv /home/ec2-user/data/train.csv
            aws s3 cp s3://my-titanic-data-bucket-2025/titanic/test.csv  /home/ec2-user/data/test.csv

            # 2) Docker イメージをプル＆実行
            docker pull 0nulu/titanic-ml-pipeline:latest
            docker run --rm \
              -v /home/ec2-user/data:/app/data \
              0nulu/titanic-ml-pipeline:latest